TARGET = test
BUILD  = build

CC      = riscv32-MINIRISC-elf-gcc
LD      = riscv32-MINIRISC-elf-gcc
OBJCOPY = riscv32-MINIRISC-elf-objcopy
OBJDUMP = riscv32-MINIRISC-elf-objdump
SIZE    = riscv32-MINIRISC-elf-size

CFLAGS  += -march=rv32im_zicsr -W -Wall -O2
CFLAGS  += -nostartfiles
LDFLAGS += -Wl,-Ttext=0x80000000

SRCS = $(wildcard *.S)
OBJS = $(addprefix $(BUILD)/, $(SRCS:.S=.o))
DEPS = $(OBJS:.o=.d)

.PHONY: all clean lss
all: $(BUILD)/$(TARGET).bin

-include $(DEPS)

$(BUILD)/%.o: %.S
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -x assembler-with-cpp -c $< -o $@ -MMD -MP -MF"$(@:%.o=%.d)"

$(BUILD)/$(TARGET).elf: $(OBJS)
	$(LD) -o $@ $(filter %.o,$^) $(CFLAGS) $(LDFLAGS)
	@echo "────────────────────────────────────────"
	@$(SIZE) $@
	@echo "────────────────────────────────────────"

$(BUILD)/$(TARGET).bin: $(BUILD)/$(TARGET).elf
	$(OBJCOPY) -O binary $< $@

$(BUILD)/$(TARGET).lss: $(BUILD)/$(TARGET).elf
	$(OBJDUMP) -h -D $< > $@

lss: $(BUILD)/$(TARGET).lss
	less $<

clean:
	@rm -rf $(BUILD)
